LedgerHQ/python-erc7730

- pyproject.toml
default backend does not pickup git tag version
> fix: switch back to pep517

- src/erc7730/common/abi.py
- src/erc7730/lint/common/paths.py
- tests/common/test_abi.py
- tests/lint/test_lint.py
- Generate array ABI path for array types
- Move to regex-based substitution rather than incomplete parsing for `reduce_signature`
First fix is not enough to fix linter issues on https://github.com/LedgerHQ/clear-signing-erc7730-registry/blob/master/registry/paraswap/calldata-AugustusSwapper.json however second fix should allow to progress on https://github.com/LedgerHQ/clear-signing-erc7730-registry/pull/56
> fix: improve ABI paths discovery and signature reduction

- src/erc7730/common/abi.py
- tests/common/test_abi.py
- Use Lark to parse signature
- Transform it to `erc7730.model.abi.Function`
- Rely on `eth_utils.abi.abi_to_signature` for reduction
> feat: parse ABI signature

- src/erc7730/main.py
- tests/test_main.py
Example:
```
$ erc7730 resolve tests/registries/clear-signing-erc7730-registry/registry/lido/calldata-stETH.json
```
> feat: add `erc7730 resolve` command to convert descriptor to resolved form

- pdm.lock
- pyproject.toml
- src/erc7730/common/client.py
- src/erc7730/common/output.py
- src/erc7730/convert/resolved/convert_erc7730_input_to_resolved.py
- src/erc7730/lint/lint.py
- src/erc7730/lint/lint_validate_abi.py
- tests/common/test_client.py
- tests/test_main.py
- only `ETHERSCAN_API_KEY` is required now
- switch client from `requests` to `httpx` (HTTP 2, typed, more easily extensible)
- add disk cache to HTTP client
- add etherscan rate limiting on HTTP client
- add support for `file://` protocol on HTTP client
- improve HTTP client interface to not require `RootModel` anymore
unrelated changes:
- multithread linter
- cosmetic/output improvements to linter
> feat: support all Etherscan based chains, add support for `file://` URLs, improve linter outputs

- pyproject.toml
- `shell` is required for "more shell-specific tasks, such as pipeline and output redirecting"
- correct `composite` format
> chore: slightly better pdm scripts

- src/erc7730/convert/resolved/convert_erc7730_input_to_resolved.py
Some formats require parameters to be set, but this is not enforced, leading to invalid resolved descriptors
Registry fixes: https://github.com/LedgerHQ/clear-signing-erc7730-registry/pull/67
> fix: fix presence of `params` not enforced when parameters are mandatory

- src/erc7730/model/display.py
- src/erc7730/model/input/display.py
- src/erc7730/model/resolved/display.py
`sources` are now free form strings since https://github.com/LedgerHQ/clear-signing-erc7730-registry/pull/23
> fix: fix trusted names sources

- src/erc7730/common/output.py
- src/erc7730/lint/lint.py
we want:
- default console output adder to print file paths (used in CAL)
- `lint` to not print it (it uses sections)
- `lint --gha` to print it
> fix: fix default console output not printing file path

- docs/pages/usage_library.md
- src/erc7730/convert/resolved/convert_erc7730_input_to_resolved.py
- src/erc7730/main.py
- src/erc7730/model/input/descriptor.py
- src/erc7730/model/resolved/__init__.py
- src/erc7730/model/resolved/descriptor.py
- tests/convert/resolved/data/nested_fields_eip712_array_input.json
- tests/convert/resolved/data/nested_fields_eip712_array_resolved.json
- tests/convert/resolved/data/nested_fields_eip712_struct_input.json
- tests/convert/resolved/data/nested_fields_eip712_struct_resolved.json
- tests/convert/resolved/test_convert_input_to_resolved.py
During resolution, nested fields are:
- flattened if path points to a struct or array element
- preserved if path points to an array
- forbidden if path points to an array slice
> feat(BACK-7910): implement handling of nested fields

- src/erc7730/common/client.py
- src/erc7730/common/output.py
- src/erc7730/common/pydantic.py
- src/erc7730/convert/ledger/eip712/convert_eip712_to_erc7730.py
- src/erc7730/convert/ledger/eip712/convert_erc7730_to_eip712.py
- src/erc7730/convert/resolved/constants.py
- src/erc7730/convert/resolved/convert_erc7730_input_to_resolved.py
- src/erc7730/convert/resolved/parameters.py
- src/erc7730/convert/resolved/references.py
- src/erc7730/lint/lint.py
- src/erc7730/lint/lint_validate_abi.py
- src/erc7730/lint/lint_validate_display_fields.py
- src/erc7730/model/display.py
- src/erc7730/model/input/display.py
- src/erc7730/model/input/path.py
- src/erc7730/model/types.py
- tests/convert/resolved/data/definition_format_nft_name_resolved.json
- tests/convert/resolved/data/unsupported_using_literal_values_as_constants_input.json
- tests/convert/resolved/data/unsupported_using_literal_values_input.json
- tests/convert/resolved/test_convert_input_to_resolved.py
- tests/model/data/errors/format_token_amount_native_currency_address_using_data_path.json
- tests/model/test_model_validation.py
- improve output for some particular errors (HTTP responses, addresses used instead of paths)
- sanitize pydantic errors
- customize errors for specific types (path, base types, unions)
- sort and deduplicate linter outputs
- minor wording improvements
This fixes bad error output in https://github.com/LedgerHQ/clear-signing-erc7730-registry/pull/33
> feat(BACK-7924): improve error handling

- pdm.lock
- pyproject.toml
- src/erc7730/common/abi.py
- src/erc7730/convert/ledger/eip712/convert_eip712_to_erc7730.py
- src/erc7730/convert/ledger/eip712/convert_erc7730_to_eip712.py
- src/erc7730/convert/resolved/convert_erc7730_input_to_resolved.py
- src/erc7730/generate/generate.py
- src/erc7730/generate/schema_tree.py
- src/erc7730/lint/classifier/__init__.py
- src/erc7730/lint/classifier/eip712_classifier.py
- src/erc7730/lint/lint_transaction_type_classifier.py
- src/erc7730/lint/lint_validate_display_fields.py
- src/erc7730/main.py
- src/erc7730/model/context.py
- src/erc7730/model/input/context.py
- src/erc7730/model/paths/path_schemas.py
- src/erc7730/model/resolved/context.py
- tests/generate/data/abis001.json
- tests/generate/data/schemas001.json
- tests/generate/test_generate.py
- tests/model/paths/test_path_schemas.py
- tests/test_main.py
Notes:
- The generator does its best to guess proper format based on name+type. it is perfectible but a good enough start point
- Tree code is [extracted from CAL](https://github.com/LedgerHQ/crypto-assets/blob/main/src/crypto_assets/common/erc7730/calldata/convert/v1/abi.py) but it diverged significantly
- Test don't cover much, only really tested manually with some examples:
```
pdm run erc7730 generate --chain-id=1 --address=0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9
pdm run erc7730 generate --chain-id=1 --address=0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45
pdm run erc7730 generate --chain-id=1 --address=0x0000000000000000000000000000000000000000 --abi tests/generate/data/abis001.json
pdm run erc7730 generate --chain-id=1 --address=0x0000000000000000000000000000000000000000 --schema …
```
> feat(BACK-7925): implement `erc7730 generate` command

- docs/pages/usage_cli.md
Shouldn't have let copilot write the doc
> doc: fix typos

- src/erc7730/model/paths/__init__.py
- src/erc7730/model/paths/path_parser.py
- tests/model/paths/test_path_parser.py
Update following https://github.com/LedgerHQ/clear-signing-erc7730-registry/pull/83
- start and end are optional
- end is exclusive
> chore(BACK-8009): update slices support

- src/erc7730/convert/ledger/eip712/convert_erc7730_to_eip712.py
- tests/assertions.py
- tests/convert/ledger/eip712/data/eip712-UniswapX-DutchOrder.json
- tests/convert/ledger/eip712/test_convert_erc7730_to_eip712.py
- tests/skip.py
Added test by reference to ensure we output same descriptor as legacy registry: https://github.com/LedgerHQ/ledger-asset-dapps/blob/main/ethereum/uniswap/eip712.json#L226
> fix(BACK-8037): EIP-712 conversion must not use format=amount inside arrays

- src/erc7730/convert/resolved/values.py
- src/erc7730/model/resolved/display.py
- tests/convert/resolved/data/literal_values_resolved.json
related: https://github.com/LedgerHQ/crypto-assets/pull/1585
> feat(BACK-8135): add type info to constants

- .pre-commit-config.yaml
- src/erc7730/generate/generate.py
- src/erc7730/main.py
- tests/generate/test_generate.py
**Breaking change**
`generate.generate_descriptor` interface change: method now expects either string or bytes rather than path. Path should be resolved by caller.
```python
generate_descriptor(chain_id=..., contract_address=..., abi_file="/path/to/abi.json")
```
Should be replaced by:
```python
with open("/path/to/abi.json", "rb") as f:
generate_descriptor(chain_id=..., contract_address=..., abi=f.read())
```
CLI is unchanged.
> feat(BACK-8208): tooling: Allow generation from string inputs

- .pre-commit-config.yaml
- pdm.lock
- pyproject.toml
- src/erc7730/convert/ledger/eip712/convert_eip712_to_erc7730.py
- src/erc7730/convert/ledger/eip712/convert_erc7730_to_eip712.py
- src/erc7730/model/paths/__init__.py
- tests/convert/ledger/eip712/data/eip712-UniswapX-DutchOrder.json
- tests/convert/ledger/eip712/test_convert_eip712_round_trip.py
- tests/convert/ledger/eip712/test_convert_erc7730_to_eip712.py
- Special case for `"local"` as stated in ERC-7730 docs that converts to `local_address_book` enum value
- Default to all sources if empty to mirror ERC7730 calldata behaviour (not in this repo)
> feat(BACK-8213): EIP-712 trusted names support

- src/erc7730/model/input/display.py
Context:
https://github.com/LedgerHQ/clear-signing-erc7730-registry/actions/runs/13637196842
> fix: Allow zero-size fields in display

- pdm.lock
- src/erc7730/common/ledger.py
- src/erc7730/convert/calldata/convert_erc7730_input_to_calldata.py
- src/erc7730/convert/resolved/convert_erc7730_input_to_resolved.py
- src/erc7730/lint/lint.py
- src/erc7730/lint/lint_validate_max_length.py
- src/erc7730/model/calldata/v1/instruction.py
- tests/common/test_client.py
- Convert Etherscan V1 to V2 URL in converter
- Update Etherscan V2 supported chains
- dependencies update from https://github.com/LedgerHQ/python-erc7730/pull/206
- submodules update from https://github.com/LedgerHQ/python-erc7730/pull/207
- Remove hardcoded length limit in Ledger CallData descriptors
- Emit warning in linter if length limit is broken
Example output: 
```
➡️ checking tests/registries/clear-signing-erc7730-registry/registry/swell/calldata-swell.json…
🟠 warning: Display intent too long: Display intent(s) `Add to whitelist a single address, Moves `amount` tokens from `from` to `to` using the allowance mechanism, Remove several addresses from whitelist, Set node
operator reward percentage, Set maximum reprice difference percentage, Set swell treasury reward percentage, Add …
```
> chore: repository maintenance
